### Cria novo atendimento
POST https://localhost:5001/api/atendimento/create/2/1

### Chama próximo paciente para atendimento
GET https://localhost:5001/api/atendimento/get-prox/

### Mostra a fila para atendimento
GET https://localhost:5001/api/atendimento/lista/

### Envia paciente para triagem - Chama o paciente para o atendimento (libera o paciente, altera o valor do boolean)
GET https://localhost:5001/api/atendimento/next/

