### Cadastrar novo paciente
POST https://localhost:5001/api/paciente/create
Content-Type: application/json

{
    "ConvenioNome" : "Amil",
    "Nome" : "José",
    "Sobrenome" : "Duarte",
    "Cpf" : "321",
    "Idade" : "35",
    "Telefone" : "999999",
    "Email" : "jose@email",
    "Endereco" : "rua dos piratas"
}

### Cadastrar novo paciente
POST https://localhost:5001/api/paciente/create
Content-Type: application/json

{
    "ConvenioNome" : "Unimed",
    "Nome" : "Bruno",
    "Sobrenome" : "Silva",
    "Cpf" : "123",
    "Idade" : "35",
    "Telefone" : "999999",
    "Email" : "bruno@email",
    "Endereco" : "rua dos piratas"
}

### Cadastrar novo paciente
POST https://localhost:5001/api/paciente/create
Content-Type: application/json

{
    "ConvenioNome" : "Amil",
    "Nome" : "Roger",
    "Sobrenome" : "D.",
    "Cpf" : "123456",
    "Idade" : "35",
    "Telefone" : "999999",
    "Email" : "goldRoger@email",
    "Endereco" : "rua dos piratas"
}

### Listar todos os pacientes
GET https://localhost:5001/api/paciente/list

### Buscar paciente pelo id
GET https://localhost:5001/api/paciente/getbyid/1

### Buscar paciente pelo nome
GET https://localhost:5001/api/paciente/getbyname/Roger

### Deletar um paciente pelo id
DELETE https://localhost:5001/api/paciente/delete/2

### Atualizar um paciente pelo id
PUT https://localhost:5001/api/paciente/update
Content-Type: application/json

{
    "Id": 1,
    "ConvenioId" : 2,
    "Nome" : "Maria",
    "Sobrenome" : "Eduarda",
    "Matricula" : "123",
    "Cpf" : "123",
    "Idade" : "35",
    "Telefone" : "999999",
    "Email" : "maria@email",
    "Endereco" : "rua dos piratas"
}
