### Cadastrar um novo sintoma
POST https://localhost:5001/api/sintoma/create
Content-Type: application/json

{
    "Nome" : "Dor",
    "GrauIntensidade" : "7"
}

### Cadastrar um novo sintoma
POST https://localhost:5001/api/sintoma/create
Content-Type: application/json

{
    "Nome" : "Febre",
    "GrauIntensidade" : "9"
}

### Cadastrar um novo sintoma
POST https://localhost:5001/api/sintoma/create
Content-Type: application/json

{
    "Nome" : "Nausea",
    "GrauIntensidade" : "3"
}

### Listar todos os sintomas
GET https://localhost:5001/api/sintoma/list

### Buscar um sintoma pelo id
GET https://localhost:5001/api/sintoma/getbyid/1

### Deletar um sintoma pelo id
DELETE https://localhost:5001/api/sintoma/delete/1

### Alterar um sintoma pelo id
PUT https://localhost:5001/api/sintoma/update
Content-Type: application/json

{
    "Id" : 2,
    "Nome" : "Cansaço",
    "GrauIntensidade" : "10"
}